export const SIGN_IN_STEP = {
  DONE: "DONE",
  CONFIRM_SIGN_UP: "CONFIRM_SIGN_UP",
  RESET_PASSWORD: "RESET_PASSWORD",
  CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED: "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED",
};
