import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// const cognitoAuthConfig = {
//   authority: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_AP1FB3AyT",
//   client_id: "6v5j434nrlk0brkrl9v0fcd25k",
//   redirect_uri: "https://d84l1y8p4kdic.cloudfront.net",
//   response_type: "code",
//   scope: "phone openid email",
// };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

